version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "UTC"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "daily"
      time: "08:10"
      timezone: "UTC"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
      time: "08:20"
      timezone: "UTC"
    open-pull-requests-limit: 10
